from mako.template import Template
import json

serialization_template_str = '''
/**************************************************
* auto generated by reflection system
**************************************************/

${headers}

namespace FishEngine
{
	${serialize_functions}
} // namespace FishEngine
'''
serialization_template = Template(serialization_template_str)

serialization_function_template_str = '''
	// ${T}
	template<typename Archive>
	void Save ( Archive& archive, ${T} const & value )
	{
		${serialize_seqs}
	}

	template<typename Archive>
	void Load ( Archive& archive, ${T} & value )
	{
		${deserialize_seqs}
	}
'''
serialization_function_template = Template(serialization_function_template_str)

skip_types = ()

def GenSerializationFunctions(classinfo):
    headers = []
    functions = []
    visited = set()
    # def register(classname):
    #     if classname in visited:
    #         return
    #     c = classinfo[classname]
    #     visited.add(classname)

    for key in classinfo.keys():
        #register(key)
        if key in skip_types:
            continue
        c = classinfo[key]
        headers.append(c['header_file'])
        serialize_seqs_list = [x for x in c['members'] if not x['NonSerializable']]
        serialize_seqs = ['archive << make_nvp("{0}", value.{0}); // {1}'.format(x['name'], x['type']) for x in serialize_seqs_list]
        if 'parent' in c:
            p = 'archive << BaseClassWrapper<{0}>(value);'.format(c['parent'])
            serialize_seqs.insert(0, p)
        serialize_seqs = '\n\t\t'.join(serialize_seqs)
        deserialize_seqs = serialize_seqs.replace('<<', '>>')
        f = serialization_function_template.render(namespace=c['scope_prefix'], T=key, serialize_seqs=serialize_seqs, deserialize_seqs=deserialize_seqs)
        functions.append(f)

    headers = '\n'.join(['#include "../{}"'.format(x) for x in headers])
    serialize_functions = '\n'.join(functions)
    return serialization_template.render(headers = headers, 
        serialize_functions=serialize_functions)

#register_teamplate
componentInheritance_template_str = '''
static std::map<std::string, std::string> s_componentInheritance =
{
    ${pairs}
};
'''

classname_template_str = '''

'''

def GenComponentInheritance(class_info):
    def IsComponent(name):
        #print(name)
        if name == "Component":
            return True
        if 'parent' not in class_info[name]:
            return False
        return IsComponent(class_info[name]['parent'])

    pairs = []
    for key in class_info.keys():
        if "Component" == key:
             pairs.append((key, ''))
        elif IsComponent(key):
            pairs.append((key, class_info[key]['parent']))
    pairs = ['{{"{0}", "{1}"}},'.format(x, y) for (x, y) in pairs]
    #print(pairs)
    print(Template(componentInheritance_template_str).render(pairs='\n\t'.join(pairs)))

DynamicSerializeObject_template_str = '''
namespace FishEngine
{
    template<class Archive>
    static void DynamicSerializeObject(Archive & archive, std::shared_ptr<Object> obj)
    {
        const int id = obj->ClassID();
        switch (id)
        {
        ${dynamic_seqs};
        default:
            abort();
        }
    }
}
'''

DynamicSerializeObject_seq = '''
        case ClassID<{0}>():
            archive << *std::dynamic_pointer_cast<{0}>(obj);
            break;'''

def Gen_DynamicSerializeObject(class_info):
    def IsObject(name):
        if name == "Object":
            return True
        if 'parent' not in class_info[name]:
            return False
        return IsObject(class_info[name]['parent'])

    Objects = []
    for key in class_info.keys():
        if IsObject(key):
            Objects.append(key)
    Objects.remove("Object")
    seqs = ''.join([DynamicSerializeObject_seq.format(x) for x in Objects])
    return Template(DynamicSerializeObject_template_str).render(dynamic_seqs = seqs)

def GenSerialization(class_info):
    dynamic_serialize = Gen_DynamicSerializeObject(class_info)
    return GenSerializationFunctions(class_info) + dynamic_serialize


if __name__ == "__main__":
    with open('temp/class.json') as f:
        class_info = json.loads(f.read())
    GenComponentInheritance(class_info)
    with open('../../Engine/Source/Runtime/generate/Class_Serialization.hpp', 'w') as f:
        f.write(GenSerialization(class_info))
    

